ECHO OFF
ECHO =========================================
ECHO   Starting Server on Port 1234
ECHO =========================================
ECHO  Open Browser to http://localhost:1234/
server.py 1234
ECHO        ....................
ECHO          ................  
ECHO            ............    
ECHO              ........    
ECHO                ....   
ECHO                 ..   
ECHO Server stopped