rd /S /Q "D:\Dev\LudumDare\LD08 Swarms\.svn"
rd /S /Q "D:\Dev\LudumDare\LD15 Caverns\LD_Caverns.suo"
rd /S /Q "D:\Dev\LudumDare\LD15 Caverns\LD_Caverns\LD_Caverns.suo"
rd /S /Q "D:\Dev\LudumDare\LD15 Caverns\LD_Caverns\Caverns\ProgImg\.picasa.ini"
rd /S /Q "D:\Dev\LudumDare\LD17\LD17.suo"
rd /S /Q "D:\Dev\LudumDare\LD19 Discover\.git"
rd /S /Q "D:\Dev\LudumDare\LD22 Alone\.git"
rd /S /Q "D:\Dev\LudumDare\LD22 Alone\LD_Alone.suo"
rd /S /Q "D:\Dev\LudumDare\LD22 Alone\LD_Alone.v11.suo"
rd /S /Q "D:\Dev\LudumDare\LD22 Alone\LD_Alone.v12.suo"
rd /S /Q "D:\Dev\LudumDare\LD22 Alone\LD_Alone\Flock\.svn"
rd /S /Q "D:\Dev\LudumDare\LD22 Alone\LD_Alone\OpenGL\.svn"
rd /S /Q "D:\Dev\LudumDare\LD26\.git"
rd /S /Q "D:\Dev\LudumDare\LD27 TenSec\LD27 TenSec.v12.suo"
rd /S /Q "D:\Dev\LudumDare\LD28\.git"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\BuildLogic.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\BurnContain.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Climber Anims.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Climber New.controller.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Climber.unity.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\ClimberController.controller.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\ClimberLogic.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Editor.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Explode.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\FollowCam.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\HideAfter.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\hostage.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\HostageLogic.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\JetpackFire.controller.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\JetpackGuy.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\JetpackTest.unity.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\KillWhenDone.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Materials.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\New Climber Anims.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Plugins.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Ripped Arms.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\TileRef.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Victim.controller.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Arm Rip Fall L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Arm Rip Fall R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Arm Rip L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Arm Rip R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Arm Rip Splat L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Arm Rip Splat R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Climbing L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Climbing R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Idle L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Idle R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Jump Left.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Jump Right.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Jump Up L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Climb Jump Up R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Falling L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Falling R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\FireIdle.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\FireLoop.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\FireUp.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Hat Floor L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Hat Floor R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Splat L.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Splat R.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Victim Back.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Victim Idle.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Anims\Victim Scream.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Climber Anims\Idle.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Editor\TilePal.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Materials\Smoke.mat.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Materials\Stars.mat.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Materials\Tiles.mat.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\New Climber Anims\Idle.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\New Climber Anims\Jump Left.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\New Climber Anims\Jump Right.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\New Climber Anims\Jump Up.anim.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Plugins\BuildTile.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\backTest.jpg.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\Climber.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\GameOver.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\guy.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\guy_parts.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\message.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\road.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\stars.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\street-lamp.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\testguy.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\testplatforms.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Sprites\tiles.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Brick Left Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Brick Right Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Brick Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Crossbar Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Mid Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Roof Left Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Roof Right Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Roof Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Shutter Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Blown Window Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Brick Left Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Brick Right Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Brick Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Grey Left Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Grey Right Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Grey Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Roof Left Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Roof Right Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Roof Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Shutter Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD28\Assets\Tiles\Window Tile.prefab.meta"
rd /S /Q "D:\Dev\LudumDare\LD29\.git"
rd /S /Q "D:\Dev\LudumDare\LD30 Warm\Assets\backdrop.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD30 Warm\Assets\square.png.meta"
rd /S /Q "D:\Dev\LudumDare\LD30 Warm\Assets\TetGame.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD30 Warm\Assets\TetPiece.cs.meta"
rd /S /Q "D:\Dev\LudumDare\LD30 Warm\Assets\tetTest.unity.meta"
rd /S /Q "D:\Dev\LudumDare\LD30ConnectedWorlds\.git"